### PR TITLE
Sort tree view by cyclepoints and task names

### LINKED ISSUE #469: Consistent sorting of cycle points in the tree view
**Describe the bug**

Using the latest version of the deltas branch in the UI, and with the SoD branch, I got some cycle points out of order, apparently.

image

I think it should be either 8 - 9 - 10, or 10 - 9 - 8, but definitely not 10 - 8 - 9.

**Release version(s) and/or repository branch(es) affected?**

SoD cylc flow, and UI deltas branch. UIS on master.

**Steps to reproduce the bug**

**Expected behavior**

Consistent order of cycle points.

**Screenshots**

image

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by kinow**
These changes close #469 

These changes partially address #333 (see https://github.com/cylc/cylc-ui/issues/333#issuecomment-651600058)

Cycle points showing newest data first. Tasks in alphabetical order, by name. Jobs by submit number, reverse (we display the first only, which is the latest).

We do not need to sort the deltas when updating or removing data. As the data returned is used to update existing data and nodes in the UI.

We are also not sorting the cycle points. The reason is that the cycle points are added to the tree one after the other. So if we already have data in the UI, adding new data, even if in order to the JS data, the browser won't display in order. It will just append the new data (in order) after the existing data.

So because of that, the cycle points are returned in any order. And then we modify the existing cycle point sorting code (i.e. we were already sorting in JS, so no performance issue here IMO) to just show the newest cycle point first.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

File: src/graphql/queries.js [hunk 1]
```diff
@@ -53,41 +53,41 @@ fragment WorkflowTreeDeltas on Deltas {
 fragment WorkflowTreeAddedData on Added {
   workflow {
     ...WorkflowData
-    cyclePoints: familyProxies(ids: ["root"], ghosts: true) {
+    cyclePoints: familyProxies (ids: ["root"], ghosts: true) {
       cyclePoint
     }
-    taskProxies(sort: { keys: ["cyclePoint"] }, ghosts: true) {
+    taskProxies (sort: { keys: ["name"], reverse: false }, ghosts: true) {
```
Comment (kinow) [inline src/graphql/queries.js:59]: That's why there was no order in the tasks. They were being sorted by cycle point (can't tell why, probably my bad :smile: ). Now sorting by name.

**Comment by kinow** [comment]
Result after this PR.

image

**Comment by kinow** [comment]
I think it would be nice to allow the user to choose whether the new or old cycle points are displayed first, but probably part of #333, and we would need to choose where to add a component showing that option. So work for another ticket/PR IMO :+1:

**Comment by oliver-sanders** [comment]
> I think it would be nice to allow the user to choose whether the new or old cycle points are displayed first

Because of job ordering it might be best not to make this configurable to avoid the confusion of having opposite sorting in the same window.

**Comment by oliver-sanders** [comment]
Can the tasks get out of order when deltas arrive containing new tasks not present before?

**Comment by kinow** [comment]
> Can the tasks get out of order when deltas arrive containing new tasks not present before?

Only if the new tasks arrive in the `updated` delta. But I think they must always be in the `added`.

When we get these new tasks, their family and cyclepoint parents must either be included in this current `delta.added` payload, or, be already present (no sure if possible?).

I tried thinking of a workflow where I would have the parent of tasks (cycle point or family) present and with tasks, and then new tasks not already present in the UI arrived. But I couldn't come up with a good example. Is that possible @oliver-sanders ? 

If so I guess we could get the tasks out of order just like cycle points, and need to sort them in the frontend.

**Comment by kinow** [comment]
Rebased, resolved conflicts.

**Comment by oliver-sanders** [comment]
Sorry, I managed to get the tasks out of order:

Screenshot 2020-09-09 at 11 43 02

However, there was quite a lot going wrong with the UI for my example, many cycles are showing simultaneously with tasks in funny states, so it might not be the sorting that was going wrong?

I used this workflow:

```ini
[scheduling]
    initial cycle point = 1
    cycling mode = integer
    [[graph]]
        P1 = """
            a[-P1] => a
            b[-P2] => b
            c[-P3] => c
            d[-P4] => d
            e[-P5] => e
            f[-P6] => f
        """

[runtime]
    [[root]]
        script = sleep 1
```

**Comment by kinow** [comment]
That's great @oliver-sanders ! With the example workflow I can try to reproduce this tomorrow or Friday and see what's going on. Thanks for testing again!

**Comment by kinow** [comment]
@oliver-sanders I used your example workflow, and could successfully reproduce it.

I'm preparing Cylc UI to **maybe** demo it today in the RSE conference over here. So I've switched to Cylc Flow 8.0a2 and Cylc UI Server 0.2, and then I cannot reproduce the out-of-order issue with your workflow anymore.

I'll investigate a bit more to understand if the GraphQL queries are returning the nodes in the right order on `master`. If it is, then I will try to understand why I couldn't reproduce it with the latest release.

**Comment by kinow** [comment]
Alright, understood what's going on.

image

image

The cycle point 395 got `b` and then `d`. Later, in another deltas.added payload, we receive the `395.c`. Which causes Vue to keep the `395.b` and `395.d` UI elements in-place (re-using when updates are received, for performance) and then appends `395.c` after `395.d`.

Now let me see how this can be solved… :nerd_face:

**Comment by kinow** [comment]
All right, tests passing, ready for review again. Had to sort in the UI too due to some cases where the data could be displayed incorrectly in the UI (as @oliver-sanders 's example shows).

Didn't remove the backend sorting, as in the best case we might get the data correctly sorted, so the JS `Array.sort` algorithm would perform in the best-case-scenario—but happy to remove that if others prefer :+1:

**Comment by oliver-sanders** [comment]
Tested with the same example again, tasks appear in the correct order 👍 

I am still seeing many more cycle points than I would expect to see, however, I've managed to replicate this on master so I'll raise a new issue for that.

File: src/mixins/treeitem.js [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+          // sort cycle point children (family-proxies, and task-proxies)
+          // first we sort by type ascending, so 'family-proxy' types come before 'task-proxy'
+          // then we sort by node name ascending, so 'bar' comes before 'foo'
+          return orderBy(children, [child => child.type, child => child.node.name.toLowerCase()], ['asc', 'asc'])
+        }
+        case 'family-proxy': {
+          // sort family-proxy children (family-proxies, and task-proxies)
+          // first we sort by type ascending, so 'family-proxy' types come before 'task-proxy'
+          // then we sort by node name ascending, so 'bar' comes before 'foo'
+          return orderBy(children, [child => child.type, child => child.node.name.toLowerCase()], ['asc', 'asc'])
```
Comment (oliver-sanders) [inline src/mixins/treeitem.js:66]: Follow on:

It might be nice to have the families appear before the tasks similarly to how some file listings put directories before files.

Because of the Cylc naming convention of lower-case for tasks, upper-case for families removing the `toLowerCase` would achieve this.

Do we think people would universally prefer this, should it be configurable?

File: src/mixins/treeitem.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+        }
+        case 'task-proxy': {
+          // sort task-proxy children (jobs)
+          // sort by node submit  descending, so '4' comes before '3'
+          return orderBy(children, ['node.submitNum'], 'desc')
```
Comment (oliver-sanders) [inline src/mixins/treeitem.js:71]: Follow on:

Would be good to include the natural sorting change made to the Cylc7 GUI so that number patterns are respected by sorting e.g:

* a_0
* a_5
* a_10
* a_15

Which currently get sorted as:

* a_0
* a_10
* a_15
* a_5

**Review by oliver-sanders — APPROVED** [review]
Ran the complex suite, couldn't find anything out of order!

File: src/mixins/treeitem.js (hunk 2 above)
Comment (kinow) [reply src/mixins/treeitem.js:66]: >It might be nice to have the families appear before the tasks similarly to how some file listings put directories before files.

That's how it should be working now. The family proxies should be displayed before the task proxies (because we order by 2 fields, first type, and then name).

>Do we think people would universally prefer this, should it be configurable?

Good question. Will leave that for follow-up question with @cylc/core

Comment (hjoliver) [reply src/mixins/treeitem.js:66]: I don't see a great need to make that configurable.  A possible future change if people want it.

File: src/mixins/treeitem.js (hunk 3 above)
Comment (kinow) [reply src/mixins/treeitem.js]: Good idea! Done!

**Review by hjoliver — APPROVED** [review]
Seems to be all working properly now, including "natural" sorting. :+1:

File: src/mixins/treeitem.js (hunk 2 above)
Comment (oliver-sanders) [reply src/mixins/treeitem.js]: I think people should be happy enough with this.
