### PR TITLE
Prevent mutation menu closing when clicking on another task or cycle

### LINKED ISSUE #916: Clicking on another cycle or task icon causes mutation menu to show and dismiss instantly
**Steps to reproduce the bug**
- Click on a cycle or task to bring up mutations menu
- Click on another cycle or task

**Expected behavior**
- The open menu should be replaced with a new menu for the most recently clicked cycle/task

**Actual behaviour**
- The new menu appears for a split second before disappearing

**Screenshots**
demo5

**Additional context**

Actually, we're reusing the same menu component, so what seems to be happening is it moves to the clicked position (✔️) and also is dismissed at the same time (❌) because it's set to dismiss when clicking outside of the menu. In the case of clicking outside of the menu but on another cycle/task, we should not dismiss it.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #916

demo6

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (e2e).
- [ ] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

File: src/components/cylc/cylcObject/plugin.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ function bind (el, binding, vnode) {
 
 function unbind (el) {
   // clean up to avoid memory issues
-  el.removeEventListener('show-mutations-menu', listener)
+  el.removeEventListener('click', listener)
```
Comment (MetRonnie) [inline src/components/cylc/cylcObject/plugin.js:56]: I think this was a mistake

**Review by AaronDCole — APPROVED** [review]
Seems to work as expected!

**Review by hjoliver — APPROVED** [review]
Looks sensible, and works for me too. 

~~I'll leave it for @wxtim to merge (sounds like he wants to look at the code more closely)~~ [Oops wrong PR for that statement!]
