### PR TITLE
made mobile burger button dark, hence actually visible

### LINKED ISSUE #898: Sidebar Uncollapse burger bar should be visible
**Describe the bug**

When testing with a small screen, I tried to open the scan bar, but struggled to see the button in the red circle.

Screen Shot 2022-01-26 at 14 42 38

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by wxtim**
These changes close #898 
**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Already covered by existing tests.
- [x] No change log entry required (very small pre-release change).
.
- [X] No documentation update required.

### CODE REVIEW

File: src/components/cylc/Toolbar.vue [hunk 1]
```diff
@@ -32,7 +32,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
       <!-- TODO: duplicated in workflow/Toolbar.vue and cylc/Toolbar.vue -->
       <!-- burger button for mobile -->
       <v-btn
-        dark
+        light
```
Comment (MetRonnie) [inline src/components/cylc/Toolbar.vue:35]: It looks like the default is `light` anyway. If we hard code it it might introduce the opposite bug when we implement dark mode #336
```suggestion
```

File: src/components/cylc/workflow/Toolbar.vue [hunk 2]
```diff
@@ -27,7 +27,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
     <!-- burger button for mobile -->
     <v-btn
       v-if="responsive"
-      dark
+      light
```
Comment (MetRonnie) [inline src/components/cylc/workflow/Toolbar.vue:30]:
```suggestion
```

**Review by MetRonnie — APPROVED** [review]

**Review by datamel — APPROVED** [review]
Thanks @wxtim
