### PR TITLE
Use deltas in GScan

### LINKED ISSUE #160: Reduce duplicated code when using WorkflowService
Just added the `WorkflowService` to `Dashboard.vue` in #149 , and noticed that ended up with some code duplicated that seems boilerplate for polling data. Some of the code may go away with WebSockets, but I suspect some of that would remain.

e.g. the methods are pretty much the same, and could be in a Object or a Mixin?

### LINKED ISSUE #209: WorkflowService doesn't work with nodesEdges, edges, or any other top level entry
The current implementation of the `WorkflowService` is tailored for a GraphQL such as 

```
{
  data: {
    workflow: {...},
    nodesEdges: {...},
    tasks: {....}
  }
}
```

The Vuex store has the methods to store the `data.workflow` object. And the service discards any other top level entry such as `nodesEdges`, `tasks`, etc. Picking only `workflow`.

But while reviewing https://github.com/cylc/cylc-flow/pull/3337 & https://github.com/cylc/cylc-uiserver/pull/70, and experimenting with Cylc UI to confirm nothing was broken, I noticed that the `WorkflowService` never populated the Vuex store.

We can work around it with GraphQL aliases, but it only works until another query is registered that overrides it by requesting `workflows {}`.

Maybe the `WorkflowService` would have to be renamed to `GraphQLService`, or simply refactored to store the `data` in the Vuex store, without picking any of its attributes.

### LINKED ISSUE #234: Use query variables in GraphQL instead of string replace
Right now our GraphQL queries in the workflow service start with

```graphql
      {
        workflows(ids: ["WORKFLOW_ID"]) {
          id
          name
          status
```

Then later in the code we 

```js
            workflowService.subscribe(
              this,
              QUERIES[queryName].replace('WORKFLOW_ID', this.workflowId)
            )
```

I am quite sure that actually we should use GraphQL query variables instead.

### LINKED ISSUE #356: Move GraphQL queries to their own modules
**Describe exactly what you would like to see in an upcoming release**

We have `graphql-tag` in our dependency tree, and we are using its `gql` for queries. One feature of `graphql-tag` is allowing for queries to be imported, just like normal modules.

This reduces cluttering and dependencies, with queries in a single place, and that can be shared among multiple components.

**Additional context**

Vue CLI UI app is an example of how that can be done: https://github.com/vuejs/vue-cli/tree/9ec2d34e652e4a7cdb9c8c956a4d67a5ea91af92/packages/%40vue/cli-ui/src/graphql

**Pull requests welcome!**

### LINKED ISSUE #388: Prevent unnecessary subscription requests
**Describe exactly what you would like to see in an upcoming release**

At the moment users may trigger unnecessary requests when visiting a URL in Cylc UI. The URL will trigger a VueRouter route/view. That view has its own lifecycle.

We have a few subscriptions being created in the `created` lifecycle of a view. A view can have multiple components. At the moment, we also have components that create subscription.

And right now, creating a subscription means an HTTP or WebSocket request to the GraphQL backend.

Given a URL visited may trigger 1 `created` method of a view, and `N` `created` methods in each of its components, we may need to re-think how this is implemented.

**Additional context**

An initial workaround was suggested here https://github.com/cylc/cylc-ui/pull/373

**Pull requests welcome!**

### LINKED ISSUE #416: WorkflowService/GQuery fetches more data than what it needs when GScan + a view/component are used
**Describe the bug**

I was looking at the Vuex data store today, and at the JS console in the browser, when I noticed that the query for my tree view was bringing more data than necessary.

When you browse the `/#/dashboard`, we have - at the moment - two queries being merged, one for the `GScan` component, and another for the `Dashboard` view. The resulting query looks like:

```graphql
    subscription {
      workflows {
        id
        name
        status
        owner
        host
        port
        taskProxies(sort: {keys: ["cyclePoint"]}) {
          id
          name
          state
          cyclePoint
          latestMessage
          task {
            meanElapsedTime
            name
          }
          jobs(sort: {keys: ["submit_num"], reverse: true}) {
            id
            batchSysName
            batchSysJobId
            host
            startedTime
            submittedTime
            finishedTime
            state
            submitNum
          }
        }
      }
    }
```

That will bring the same data for all the workflows you may be running. (We need a few more changes in the backend to simplify this query more - see #401.) 

Now when you navigate to the Tree view, you will have two queries, one for the GScan component, and one for the Tree component.

The resulting query looks like:

```graphql
subscription {
      workflows {
        id
        name
        status
        owner
        host
        port
        taskProxies(sort: {keys: ["cyclePoint"]}) {
          id
          name
          state
          cyclePoint
          latestMessage
          task {
            meanElapsedTime
            name
          }
          jobs(sort: {keys: ["submit_num"], reverse: true}) {
            id
            batchSysName
            batchSysJobId
            host
            startedTime
            submittedTime
            finishedTime
            state
            submitNum
          }
          firstParent {
            id
            name
            cyclePoint
            state
          }
        }
        familyProxies(sort: {keys: ["firstParent"]}) {
          id
          name
          state
          cyclePoint
          firstParent {
            id
            name
            cyclePoint
            state
          }
        }
      }
    }
```

So after merging it, the query will bring the complete information for the tree view of all the workflows available.

I **think** it would be better to have the Tree View information (family proxies, cycle points, mode details about jobs, etc) data just for the workflow currently being displayed. And the GScan data (workflow info and preferably no jobs/tasks info after #401) for all the workflows available.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Start 10 workflows, open the tree view of one of these workflows. You will have the tree view information in all the 10 workflows, returned from the GraphQL backend, and put in the Vuex store.

**Expected behavior**

In one bucket in the data store we would have the complete data for the tree view. In another bucket/variable/place we would have the data for the gscan (i.e. no family proxies, cycle points, job details, etc, for the GScan as that component doesn't use that data).

**Screenshots**

image

See in the screenshot above that while I am viewing the `families2` workflow, we know which workflow we want (the `workflowName` comes from the Vue router via the browser URL) but we end up with data for the `five` workflow tree view too.

**Additional context**

Possibly running 10 workflows like `complex`, then visualizing `five` would make the browser memory/cpu to have high usage for a while.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### LINKED ISSUE #453: Confirm we don't have subscriptions outliving the views/use, to avoid performance issues, and add unit/e2e tests
**Describe exactly what you would like to see in an upcoming release**

The Views and Components used in Cylc UI tell the service about their queries. When the user navigates to another View, the queries are updated.

This update (merge) must add new fields from the queries, as well as remove fields from old queries that are no longer used (e.g. user goes from dashboard to tree view, then back to dashboard; at this point there is no need for the tree view query).

I found some cases where the query appears to be left behind after the views are no longer active. That happens because the views are using `beforeDestroy`, but they are rarely destroyed (for performance).

The PR #458 had a temporary version that fixed it. It was simply tethering the subscription to the view lifecycle. It has the disadvantage that when users switch quickly between views, they may have to re-request the whole data. So one possible scenario is keeping the subscriptions open for a while.

One way or the other, we need to address this, as otherwise using the application a few hours, and switching between views and workflows would certainly cause serious performance issues in the browser and in the server due to extra GraphQL queries running unnecessarily. 

A functional test should do the following:

- [ ] Navigate to some URL or URL(s) as per scenario (e.g. dashboard -> tree, or tree -> dashboad -> user profile, etc)
- [ ] For each scenario, it must confirm the service got the right views or components registered, that the subscribed queries are correct, and that the final query contains the expected fields (can use `graphql-tag` for that if necessary)

**Additional context**

**Pull requests welcome!**

### LINKED ISSUE #542: Use deltas in GScan
**Describe exactly what you would like to see in an upcoming release**

The issue to add hierarchy to GScan #502 would benefit of having deltas in GScan. That way we can more easily update the hierarchy with the deltas.

This should also fix #416

**Additional context**

**Pull requests welcome!**

### LINKED ISSUE #625: alert: repeated errors are ignored
To prevent duplicate errors being committed to the store the Alert model checks that a new error does not match the existing one before committing the change.

Unfortunately this means that if an error occurs twice they will only be notified once, even if the have dismissed the notification.

Suggest clearing alert notifications from the store when the user dismisses them.

**Pull requests welcome!**

### LINKED ISSUE #661: Avoid data duplication in added deltas
**Describe exactly what you would like to see in an upcoming release**

We have added cyclepoints, family proxies, task proxies, and jobs being received twice, once in `deltas.added.workflow.$KEY` (where key is each of these node types), and again in `deltas.added.$KEY`.

**Additional context**

From Element today, issue raised by @hjoliver 

**Pull requests welcome!**

### LINKED ISSUE #671: UI shows loading state forever if no workflows exist
It should just show there are no workflows.

How we resolve this might depend on upcoming changes to show source workflows as well as installed ones.

shot

### LINKED ISSUE #684: Create a single object to receive the deltas of workflow-subscriptions
**Describe exactly what you would like to see in an upcoming release**

At the moment we have the `CylcTree` object which works well for the Tree View. But we want to have another structure, that is created before the `CylcTree`.

This structure will be shared by multiple workflow views, like Table view, Tree view, and Graph view.

It will receive any deltas from a workflow-subscription (ideally merged sub of all the views, to be discussed elsewhere). Once a delta is applied to this structure, it must notify any listener/observer via Vue reactivity.

**Additional context**

The `CylcTree` uses a flat lookup map (JS `Map` object). This object could be our flat object, passed around to other views, that can filter it, or derive new structure like `CylcTree`, or some `array` for the Table View.

One premise that must be followed, is to avoid duplication. So if a delta arrives for a subscription, we want to get that object from the delta, and store it only once. We can have pointers/references to this object. But we must not duplicate it.

This object should work with the current Tree view, and with the new Table view in #672 

**Pull requests welcome!**

### LINKED ISSUE #688: gscan: installed workflows
GScan no longer displays all "stopped" workflows because some workflows that are stopped have the status "INSTALLED".

We could fix this by adding "INSTALLED" to the list of the filtered states in GScan, however, I wonder if we can handle this differently...

The distinction between "INSTALLED" and "STOPPED" is quite subtle:

* **INSTALLED** Not currently running *and* hasn't run before.
* **STOPPED** Not currently running *but* has run before.

I can't remember why we [introduced the distinction](https://github.com/cylc/cylc-flow/pull/4206/files#diff-03bc1d330de598ad6b24fde7fdf98f2ad79f2f36b5fbaf8748bfb2b862cea0a8R43-R44). I think it will be confusing to users when they are filtering workflows by state. Cylc doesn't make this distinction anywhere else, for example `cylc scan` shows these "INSTALLED" flows as "STOPPED". If we need to preserve the information that the workflow has/hasn't run before we could consider adding a dedicated "(re)start number" field (like the one we log this number on workflow start).

Ideas?

### PR DESCRIPTION
**Pull request by kinow**
These changes close a lot of issues, listed below. Do not worry about assigning to me, setting milestone, etc. After the final review, and when this issue is closed, then I will go through each issue linked below, will assign and set the milestone :+1: 

- close #542 (main issue)
- close #234
  * Now there is a JS object with the variables in `SubscriptionQuery` class, that gets filled from the VueRouter + VuexStore info via the `graphql.js` mixin :+1: 
  * **code review**
- close #209 
  * Now we declare the query and callbacks. Previously, there was some code in WorkflowService & GQuery that was calling setWorkflows(data.workflow), but now the callbacks receive the data as is, and can do whatever they need with it, be it nodes, workflows, deltas, etc.
  * **code review**
- close #160
  * Achieved that by using Mixins. Should be easy to port to Vue 3 too (thought about that when trying a few different approaches).
  * **code review**
- close #356 
  * **code review**
- partially address #376 (@oliver-sanders I've got an idea to improve it)
  * We are now adding views directly to the widgets. So any view (with the right mixins) can be loaded in the Workflow view & component.
  * **code review**
- close #388 
  * By coordinating in mixins when a subscription is merged/created, and only starting it in the VueRouter navigation guard (`subscriptionView` mixin) we guarantee that we don't start subscriptions that are immediately going to be stopped.
  * **review with browser network & other developer tools**
- close #416
  * We are not mixing the GScan and Tree queries any longer, they are kept as separated GraphQL web sockets subscriptions.
  * **code review or use browser network & other developer tools**
- close #453 
  * e2e tests added, also simplified with the mixins.
  * **code review**
- close #661 
  * The workflows data (GScan, Dashboard, WorkflowsTable) is in Vuex store's `workflows.workflows`. The workflow data is stored in `workflows.lookup` (workflow subscription lookup with `id` as key, and GraphQL data as value), and Tree view data is stored in `workflows.workflow`. The Tree view is re-using the data in `workflows.lookup` when it creates `workflows.workflow`, avoiding data duplication.
  * **code review and/or vue-dev-utils browser extension, inspecting the Vuex store when browsing different views**
- close #684 
  * See above.
- close #625
  * Noticed that after dismissing the alert, I was not getting notified about the new alerts (that I knew were supposed to happen). Remembered about this issue, and added a call to `setAlert(null)` when the user dismisses the alert. Note: if the user does not dismiss the alert, once a new alert appears, it will replace the existing alert :+1: 
  * **code review**
- close #688 
  * Depends.. it should close what was originally reported, but due to recent discussion, we may either remove the issue from this list, or create a follow-up issue.
  * **code review**
- close #671 
  * One more fixed in this branch :tada: was triaging issues, then decided to test this branch. A **query** does not have an initial data burst, so the UI kept waiting forever for GScan and Dashboard queries, loading until it got some data. But now as everything in the UI is using deltas after this branch (cc @hjoliver just FWIW, you can confirm by looking at the `queries.js` file in this branch, at what's exported… there should be only subscription queries with deltas) the issue does not happen anymore.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] Appropriate change log entry included.
- [x] No documentation update required.

Notes from discussions on Element and comments here:

- [x] we can use `stateTotals` to retrieve the states in the workflow, with their count too
- [x] when showing states, we need to filter the ones that are applicable to job (i.e. filter with the `JobStatus` enum!)
- [x] we can handle when workflows are moved/renamed

### CODE REVIEW

**Comment by kinow** [comment]
Ok, rebased, and now using `workflow.states` for the GScan workflow summary. It's using the task states, instead of job states. This causes some job icons added with the state "waiting", which is not valid for a job. So for now GScan may display an empty space (as the job component doesn't know what color to use).

It's also not showing any tooltip. But we will fix it before the beta release. Still need:

- [ ] check if we need tests, and if the tests are passing
- [ ] a final round of testing before it's ready for review

Then once it's merged, adding hierarchy to GScan should be a lot easier :+1:

**Comment by kinow** [comment]
Fixed tests. Will squash some commits, and finish testing it on Monday morning :sleepy: :coffee:

**Comment by kinow** [comment]
Almost there. Manual testing found two bugs. One was when you closed all the widgets. Now the second ... when you visit a workflow tree view, everything works OK. When you reload it, the "Add View" link disappears.

Tested `master` and it doesn't happen there, only on this branch :sweat:

**Comment by kinow** [comment]
Hmm, found the reason. I had forgotten GScan was responsible for filling the Vuex global `workflows.workflows`. Now the Vue Router route finds a workflow name (e.g. `five`), and sets it in Vuex.

Then the Toolbar reacts to changes to that value. When we navigate to `/#/workflows/five`, it will get the workflow name and search the array of workflows in Vuex.

This was set by GScan before. It doesn't sound like the best way of doing it, but will fix it for now and think about how to improve it later.

**Comment by kinow** [comment]
Fixed. Playing with the Several offline workflows, I found another bug (creating a separate issue for that), probably related to #454 I think.

@oliver-sanders this one should be ready to review. One important thing is to review the deltas subscription.

I have added a new subscription to `GScan`, and finished all the work here, just to realize that it could have gone into `WorkflowService`. Should I change that, and move both the `Workflow` view subscription, and the `GScan` component subscription there?

One thing to note is that normally the application will have a subscription ID `1` created when it creates `GScan`, and that that subscription will be running forever, as the `GScan` component is never destroyed :+1: 

And from what I remember, we are not able to merge deltas subscriptions. I used query fragments, but haven't found a solution to keep the existing query-merge from `gquery.js` for deltas.

**Comment by oliver-sanders** [comment]
> And from what I remember, we are not able to merge deltas subscriptions.

Yeah, it gets messy. Conceptually it's easy:

```
subs:
    1: {a, b, {c}}
    2: {a: {d}}

incoming delta:
   {A, {C}}

internal deltas:
    1: {A, {C}}
    2: {A}
```

But in practice GraphQL isn't that abstract, need to spend some time on this one soonish to see if it's achievable easily.

File: src/components/cylc/gscan/GScan.vue [hunk 1]
```diff
@@ -158,70 +125,47 @@ export default {
...
+    const vm = this
+    this.deltasObservable = this.$workflowService.startDeltasSubscription(GSCAN_DELTAS_SUBSCRIPTION, {}, {
+      next: function next (response) {
+        const added = response.data.deltas.added
+        const updated = response.data.deltas.updated
+        const id = response.data.deltas.id
+        if (added && added.workflow && added.workflow.status) {
+          const workflow = Object.assign({}, added.workflow, vm.workflows.get(id))
+          vm.workflows.set(workflow.id, workflow)
+          vm.workflowsTracker++
```
Comment (oliver-sanders) [inline src/components/cylc/gscan/GScan.vue:140]: What is the purpose of `workflowsTracker`, I can't quite work it out.

Comment (kinow) [reply src/components/cylc/gscan/GScan.vue:140]: Vue 2 does not track reactivity of Set, Map... so you can either use a separate variable to trigger Vue's reactivity, or workaround with Vue.set, Vue.delete, maybe a watcher... in this case I thought this was the simplest solution.

And Vue3 fixes it, as you can have reactive Maps.

Comment (hjoliver) [reply src/components/cylc/gscan/GScan.vue:140]: Can you add a comment to the code, so we know what's going on here in future?

Comment (kinow) [reply src/components/cylc/gscan/GScan.vue:140]: There's one already where the variable is declared: https://github.com/cylc/cylc-ui/pull/543/files#diff-fbd6564546be7943d0780e9d928d7a79600e72699daed0fe29bbec1efae43a5fR95-R97

But I can add one here too, or try to improve that comment if necessary.

**Comment by kinow** [comment]
Fixing conflicts and rebasing in a few minutes.

**Comment by kinow** [comment]
Fixing conflicts. But will need a little more time for making sure that filter & search work with the changes for the deltas 👍

File: src/components/cylc/gscan/GScan.vue (hunk 1 above)
Comment (hjoliver) [reply src/components/cylc/gscan/GScan.vue:347]: Ah, OK, no worries.

**Comment by kinow** [comment]
Should finish fixing the tests either today or Monday. But will definitely take at least until Monday for proper testing it before it's ready for review again, sorry.

**Comment by kinow** [comment]
Unit tests should pass in the next CI run :crossed_fingers: . Now let me fix the e2e tests...

**Comment by kinow** [comment]
Hopefully last commit should get lint, unit, e2e, and build, all passing. In the meantime, doing the last checks manually.

**Comment by kinow** [comment]
One more commit, to prevent accessing `.states` from offline workflows. If CI passes, it should be ready for review. Finally :tada: :slightly_smiling_face:

**Comment by oliver-sanders** [comment]
GScan doesn't seem to respond to the addition or removal of stopped workflows. I think it might not be responding to the full range of [flow change events](https://github.com/cylc/cylc-uiserver/blob/338b973e80050e7c77158b1bdf87980f067a27b1/cylc/uiserver/workflows_mgr.py#L192-L225). Perhaps we need to add more info to the deltas?

Steps to reproduce:

1. Create a workflow called `five` (but don't run it).
2. Load the UI, you should see it in the sidebar.
3. Rename `five` -> `six`.

The `five` flow should disappear and `six` should be added.

**Comment by kinow** [comment]
Oh, never thought about renaming workflows. The UIS probably doesn't send a message telling the UIS to remove that workflow, or if does, I think the UI doesn't handle that :disappointed_relieved: 

The old code, that is not deltas-based, would handle that as it always re-rendered the whole list, so I think we can't push that to a follow-up. Will have to think about this one and confirm whether there's a solution in the UI. Otherwise will create and link an issue in UIS.

Thanks for the testing @oliver-sanders !

**Comment by kinow** [comment]
Probably the fourth time rebasing a change with `GScan.vue` in it :smile: hopefully I did not remove too much, nor left too much when fixing the conflicts.

Needs:

- [ ] see if CI will pass, otherwise fix lint/unit/e2e tests
- [ ] see if the deltas are working OK
- [ ] start working/thinking on @oliver-sanders last comment :point_up:

**Comment by kinow** [comment]
While fixing the e2e test, which doesn't look too hard to fix, noticed this in the console log:

Screenshot from 2020-12-15 15-04-31

Trying to understand where that's happening, but not clear. Somewhere in the reactivity of `GScan`, I might have made an infinite loop by chaining two watcher/computed I think.

**Comment by kinow** [comment]
Still struggling to see where the cyclic dependency is happening. So far that's what I think we have in this version of `GScan`.



So

- `workflowTracker` is updated when a delta is applied to the `workflow` `Map` (not reactive, so we trick Vue by adding +1 to this var)
- `searchWorkflows` is updated when the user types something in the input field
- `filters` is updated when the user select a new task or workflow state filters
- `filteredWorkflows` is updated if any of the three above change, creating a filtered version of the `workflow` `Map`
- `sortedWorkflows` is updated if `filteredWorkflows` change, simply sorting the `filteredWorkflows` to display in the components templates

**Comment by hjoliver** [comment]
> You may have an infinite update loop in a component render function

Trying to understand this. Is it: the render function is triggered reactively, then it updates the state of some data that triggers rendering again?

**Comment by kinow** [comment]
> > You may have an infinite update loop in a component render function
> 
> Trying to understand this. Is it: the render function is triggered reactively, then it updates the state of some data that triggers rendering again?

Yes, that's my understanding too. Normally it's not too hard to spot where's the mistake. But I'm already preparing the debugger because so far just reading the code wasn't sufficient for my brain to understand what's going on :laughing:

**Comment by kinow** [comment]
Found it. It wasn't in the JS code. It was in the HTML template. I had a `.sort()` in the array of states of a node. :man_facepalming: 

Now just need to fix one e2e.

**Comment by kinow** [comment]
>GScan doesn't seem to respond to the addition or removal of stopped workflows. I think it might not be responding to the full range of flow change events. Perhaps we need to add more info to the deltas?

@dwsutherland I think this is something that is not being discussed anywhere else, and won't be fixed with the event-driven PR you are working on.

I think it is not possible with the deltas that we have at the moment. Or is there any way to find out when a workflow is deleted/renamed?

**Comment by oliver-sanders** [comment]
I think that the required data is present in the deltas in the `workflow { status }` field.

In this example I do the following:

* Create a workflow
* Start it
* Hold it
* Release it
* Stop it
* Remove it

state-changes

But there is something very strange going on. The workflow keeps showing up as added, even when it was only updated and sometimes the status is in the added part and sometimes it is in the updated part.

**Comment by oliver-sanders** [comment]
Here's an example using `stripNull`:

```graphql
subscription {
  deltas(initialBurst: true) {
    id
    added(stripNull: true) {
      workflow {
        id
        status
      }
    }
    updated(stripNull: true) {
      workflow {
        id
        status
      }
    }
  }
}
```

in GraphiQL the "status" field in the updated delta keeps flickering, the status disappears and reappears regularly ever 8-10 seconds.

The `cylc scan` update is scheduled every 5 seconds so it seems unlikely that it would be the cause, I tried with this diff:

```diff --git a/cylc/uiserver/workflows_mgr.py b/cylc/uiserver/workflows_mgr.py
index 0a26aab..9fc415c 100644
--- a/cylc/uiserver/workflows_mgr.py
+++ b/cylc/uiserver/workflows_mgr.py
@@ -243,34 +243,44 @@ class WorkflowsManager:
         async for wid, before, after, flow in self._workflow_state_changes():
             # handle state changes
             if before == 'active' and after == 'inactive':
+                logger.debug(f'active => inactive: {wid}')
                 await self._disconnect(wid)
                 await self._stop(wid)
 
             elif before == 'active' and after is None:
+                logger.debug(f'active => None: {wid}')
                 await self._disconnect(wid)
                 await self._unregister(wid)
 
             elif before is None and after == 'active':
+                logger.debug(f'None => active: {wid}')
                 await self._register(wid, flow)
                 await self._connect(wid, flow)
 
             elif before is None and after == 'inactive':
+                logger.debug(f'None => inactive: {wid}')
                 await self._register(wid, flow)
 
             elif before == 'inactive' and after == 'active':
+                logger.debug(f'inactive => active: {wid}')
                 await self._connect(wid, flow)
 
             elif before == 'inactive' and after is None:
+                logger.debug(f'inactive => None: {wid}')
                 await self._unregister(wid)
 
             # finally update the new states for internal purposes
             if before == 'active':
+                logger.debug('#1')
                 self.active.pop(wid)
             elif before == 'inactive':
+                logger.debug('#2')
                 self.inactive.remove(wid)
             if after == 'active':
+                logger.debug('#3')
                 self.active[wid] = flow
             elif after == 'inactive':
+                logger.debug('#4')
                 self.inactive.add(wid)
 
     async def multi_request(self, command, workflows, args=None,
```

And confirmed that no unexpected state changes are occurring.

**Comment by hjoliver** [comment]
Using @oliver-sanders example, I also see the workflow ID stay in **added** forever, and in **updated** _"status: running"_ flickers off briefly at intervals (every 3-20 seconds).

**Comment by kinow** [comment]
I think the empty status could be an unintentional behaviour? I don't remember @dwsutherland or someone else intentionally setting it to empty to mean that the workflow had been removed. And not sure if that would still happen after the event-driven PR is merged.

**Comment by hjoliver** [comment]
More than that, as these are *deltas* shouldn't the flow only appear in "added" once, and then in "updated" whenever its status changes?

**Comment by hjoliver** [comment]
Ah, is it because the top level flow ID appears in "added" whenever a lower-level item (e.g. a new task) is added...

**Comment by hjoliver** [comment]
From @oliver-sanders comment above:

> The workflow keeps showing up as added, even when it was only updated 

That's what I'm getting at too - "added" is supposed to show only *new* data elements, not what was new in the past and is now merely changing its value.

**Comment by dwsutherland** [comment]
> in GraphiQL the "status" field in the updated delta keeps flickering, the status disappears and reappears regularly ever 8-10 seconds.

Probably because when it disappears the status hasn't been "updated" (but some other field has).. Sometimes it will have been set as a delta (even though the status hasn't actually changed, this will need to be changed at the suite)..

> I also see the workflow ID stay in added forever,

IDs will be sent with every delta... It's hard to say what other fields had changed under `workflow`, but usually `workflow` is only added once and then updated thereafter (unless the default arguments aren't what I think they are)..

Will have to have a play

**Comment by hjoliver** [comment]
That makes sense, I think.

**Comment by kinow** [comment]
Current GScan deltas query:

```graphql
subscription OnGscanDeltasData {
  deltas(stripNull: true) {
    ...GScanTreeDeltas
    __typename
  }
}

fragment GScanTreeDeltas on Deltas {
  id
  shutdown
  added {
    ...GscanAddedData
    __typename
  }
  updated {
    ...GscanUpdatedData
    __typename
  }
  __typename
}

fragment GscanAddedData on Added {
  workflow {
    ...WorkflowData
    __typename
  }
  __typename
}

fragment GscanUpdatedData on Updated {
  workflow {
    ...WorkflowData
    __typename
  }
  __typename
}

fragment WorkflowData on Workflow {
  id
  name
  status
  owner
  host
  port
  states
  __typename
}
```

Started JupyterHub, waited for the 2 subscriptions (dashboard/Gscan) to initiate, and copied the first message with the GScan deltas query :+1:  no variables needed.

**Comment by oliver-sanders** [comment]
> Probably because when it disappears the status hasn't been "updated" (but some other field has).. Sometimes it will have been set as a delta (even though the status hasn't actually changed, this will need to be changed at the suite)..

Happy with it disappearing, don't like it reappearing, which it shouldn't do unless the value has changed.

I shifted the `id` into the `delas` field and used `stipNone`, on this platform I get a flicker every 1-3s:

flicker

**Comment by kinow** [comment]
What the tooltip is looking like now.

GIFrecord_2020-12-18_120427

**Comment by hjoliver** [comment]
Looks good!

**Comment by kinow** [comment]
> Looks good!

I tried to make it as similar as possible to Cylc 7's. Under the summary, where it shows only the task name, in the future we can edit it to say "Recent running tasks" and then include the name of the recent tasks, once we have figured out the best way to implement that in the backend :+1: 

e2e tests failing as I re-generated the mocked offline data.

**Comment by kinow** [comment]
Whew, CI passed. #559 is a trouble every time one needs to re-generate the offline data (i.e. whenever the GraphQL queries change)

**Comment by kinow** [comment]
Rebasing this one today :nerd_face:

**Comment by kinow** [comment]
Done. Had to delete and start from scratch. Even though I had re-installed everything, I had re-used an `venv` for Cylc UI Server, and apparently it refused to pick up the latest changes to the schema (no more `batchSysName`, now `jobRunnerName` I think).

I think @hjoliver had a similar issue, so without thinking twice re-created all the venvs, and this time it worked. We still have the blockers here like

- What about when a workflow is removed?
- What about when a workflow is renamed?
- Can we ignore the IDs generating new deltas even when nothing else in your query changed?

We already have the tests and changelog. So if we have the questions for these answers, this should be ready for review/merge :+1:

**Comment by oliver-sanders** [comment]
https://matrix.to/#/!SDKYnTgYyOXNBpJySp:matrix.org/$161070481195180qBQbX:matrix.org?via=matrix.org

> What about when a workflow is removed?

I think we need a "pruned" delta from the UIS for this to work properly.

> What about when a workflow is renamed?

The UIS tracks flow "registrations" not flow content so renaming is a delete event, i.e. the UIS should provide these deltas:

* pruned(flow1)
* added(flow2)

**Comment by kinow** [comment]
Rebased and did some manual testing. Same pending questions, no changes/fixes other than fixing conflicts.

**Comment by kinow** [comment]
Hmmm, tried to rebase it but getting lost with so many changes to GScan from other PR's :sweat_smile: this is pending some discussion, so will leave this one to be rebased after that discussion, since there are other PR's for GScan pending review, that are more likely to be merged first anyway :+1:

**Comment by kinow** [comment]
Picked the change that fixes the annoying `cylc-object` warnings in the console, when you run the tests, in another pull request #603 .

**Comment by kinow** [comment]
Note to self: continue rebase tomorrow, & check how to fix `generate` (using `cylc install` && `cylc run`, need to be updated) and then fix the conflicts at `checkpoint.js` :nerd_face:

**Comment by kinow** [comment]
> Note to self: continue rebase tomorrow, & check how to fix `generate` (using `cylc install` && `cylc run`, need to be updated) and then fix the conflicts at `checkpoint.js` nerd_face

Fixed. Before the `cylc install` command created a symlink, allowing the workflow to find the `get_checkpoint.py`. Now with the command installing it and using run names, the structure changed. I've changed the script to install without run names, and to copy the `get_checkpoint.py` into `~/cylc-run/one/bin/get_checkpoint.py`. `checkpoint.js` updated successfully, fixed conflicts, continuing with other conflicts.

**Comment by kinow** [comment]
Rebased. The `build` check may pass (unit tests, linter, build), but I believe e2e will fail due to the `checkpoint` data missing some tasks like the ones under `GOOD` family. Will continue investigating later today/tomorrow :+1: :coffee:

**Comment by kinow** [comment]
Even though some e2e tests are not passing, the latest commit fixes the last issue after the rebase. Deltas updating GScan. Had to disable the tasks summary until we figure out how we gonna do it with state totals, or calculating iterating tasks as before.

image

And we also still need to decide what to do when a workflow is deleted, renamed, etc.

**Comment by kinow** [comment]
Rebased due to conflicts. e2e tests should still be failing.

**Comment by kinow** [comment]
Rebased, build should still fail. But it's ready to soon use the work @dwsutherland showed yesterday with stateTotals + deltas. After this, this PR will also fix #401 (note to self: remember to link it here with closes ... later)

**Comment by kinow** [comment]
Note to self: #627 is changing GScan's query, have to confirm that rebasing doesn't mess with the GraphQL fragments, and that the fragments are updated according to the latest GScan query.

**Comment by kinow** [comment]
Starting to fix conflicts here. @dwsutherland did you think about a solution for the missing transition states in the UIS? Maybe a `state: deleted`? :grimacing: I'm probably oversimplifying how it would be fixed in the backend I think.

File: src/graphql/queries.js [hunk 2]
```diff
@@ -190,25 +218,39 @@ subscription {
...
+
+fragment GScanTreeDeltas on Deltas {
+  id
+  shutdown
+  added {
+    ...GscanAddedData
+  }
+  updated {
+    ...GscanUpdatedData
+  }
```
Comment (kinow) [inline src/graphql/queries.js:238]: Note to self: check if there's a pruned for gscan too? Can't recall if there was one and I ignored, or it simply was never there.

**Review by kinow — COMMENTED** [review]
Leaving some review notes to myself. I will need to re-read the code in `master` and the changes here to remember what I have to discard after the `latestTaskstates`, and after our fixes for layout (wrapping in GScan) pre 0.3 release. :factory_worker:

File: src/graphql/queries.js (hunk 2 above)
Comment (kinow) [reply src/graphql/queries.js:238]: Done.

The reason why I didn't include the `pruned` was that it didn't have one for workflows. Only families, jobs, tasks, and edges.

image

**Comment by kinow** [comment]
PR is up to speed with the latest development now. GScan showing workflows like in `master`, with no errors :tada: 

image

Pending only handling of removed/moved workflows :+1:

**Comment by kinow** [comment]
Had a bit of fun this morning trying to send a `workflows{ pruned: ["kinow|abc"] }` to the UI. Modified the protobuf schema in flow, and a part of the resolvers to allow `pruned` in the query schema.

Then started setting breakpoints in the UIS data_store_mgr, to the point that the `pruned` delta is accepted, but for some reason it never makes it all the way to the resolver :laughing: looks like there's some special handling for workflows and for pruned nodes that I didn't manage to update correctly.

But it was still a good exercise to learn more about Cylc UIS & Flow interactions with the data stores, schemas, GraphQL, etc.

**Comment by kinow** [comment]
Rebased. Will use this PR to review https://github.com/cylc/cylc-uiserver/pull/212

**Comment by kinow** [comment]
Rebased. Tomorrow will start testing the UIS branches with this code again :+1:  might have to change the code a bit more to support the new workflow states, and changes in the deltas.

**Comment by kinow** [comment]
Synced branches. Hadn't seen UIS PR had already been merged :sweat_smile: 

My current GraphQL query for GScan (added the `pruned.workflow` delta bit)

```graphql
subscription OnGscanDeltasData {
  deltas(stripNull: true) {
    ...GScanTreeDeltas
    __typename
  }
}

fragment GScanTreeDeltas on Deltas {
  id
  shutdown
  added {
    ...GscanAddedData
    __typename
  }
  updated {
    ...GscanUpdatedData
    __typename
  }
  pruned {
    workflow
    __typename
  }
  __typename
}

fragment GscanAddedData on Added {
  workflow {
    ...WorkflowData
    __typename
  }
  __typename
}

fragment GscanUpdatedData on Updated {
  workflow {
    ...WorkflowData
    __typename
  }
  __typename
}

fragment WorkflowData on Workflow {
  id
  name
  status
  owner
  host
  port
  stateTotals
  latestStateTasks(
    states: ["failed", "preparing", "submit-failed", "submitted", "running"]
  )
  __typename
}
```

The workflow is being deleted now. However, interestingly, in GraphiQL I get a delta with the added workflow when I add it back, but in JavaScript, the delta is **empty** :open_mouth: 

```js
{
  "id": "kinow|five",
  "shutdown": false,
  "added": {
    "__typename": "Added"
  },
  "updated": {
    "__typename": "Updated"
  },
  "pruned": {
    "__typename": "Pruned"
  },
  "__typename": "Deltas"
}
```

**Comment by kinow** [comment]
Rebased.

**Comment by kinow** [comment]
@hjoliver @oliver-sanders @dwsutherland I've added some code to handle the `deltas.pruned.workflow`. After syncing Cylc Flow, UIS, and checking out this branch, you should be able to take a look and see if GScan is behaving OK.

It should pass, hopefully, @oliver-sanders ' tests that failed last time (like deleting or renaming a workflow). If there are no issues found, then I'll add tests, squash commits, and prepare the code for a final review :tada: 

I noticed empty deltas in the deltas.workflow.added, and added `deltaStore:true` and `initialBurst: true` (see last commit), thanks to @dwsutherland . It solved the issue, but then it later occurred again. When looking at GraphiQL, I got the correct deltas. Not sure what's the cause, but @dwsutherland is aware and can help further investigating what's going on.

In the client side, you can add a `console.log(response)` [here](https://github.com/cylc/cylc-ui/pull/543/files#diff-fbd6564546be7943d0780e9d928d7a79600e72699daed0fe29bbec1efae43a5fR370) to look at the deltas returned, then play with the workflows and see what we are getting.

File: src/model/WorkflowState.model.js [hunk 3]
```diff
@@ -35,6 +36,8 @@ class WorkflowState extends Enumify {
   static STOPPING = new WorkflowState('stopping', mdiSkipNextCircle)
   static STOPPED = new WorkflowState('stopped', mdiStopCircle)
   static ERROR = new WorkflowState('error', mdiHelpCircle)
+  static INSTALLED = new WorkflowState('installed', mdiFolderPlus)
+  static UNINSTALLED = new WorkflowState('uninstalled', null)
```
Comment (kinow) [inline src/model/WorkflowState.model.js:40]: Note to self: remove this state, not in https://github.com/cylc/cylc-flow/blob/5e6ebe3cf1280e29fdc6b744d49271bb8f1cfec6/cylc/flow/workflow_status.py

File: src/components/cylc/gscan/GScan.vue [hunk 4]
```diff
@@ -280,13 +269,15 @@ export default {
...
           title: 'workflow state',
-          items: WorkflowState.enumValues.map(state => {
-            return {
-              text: state.name,
-              value: state,
-              model: true
-            }
-          })
+          items: WorkflowState.enumValues
+            .filter(state => state !== WorkflowState.UNINSTALLED)
```
Comment (hjoliver) [inline src/components/cylc/gscan/GScan.vue:273]: Remove line? (spurious state now removed!)
```suggestion
```

File: src/views/Dashboard.vue [hunk 5]
```diff
@@ -232,20 +232,21 @@ export default {
...
-        return left.text.localeCompare(right.text)
-      })
+      const count = this.workflows
+        .map(workflow => workflow.status)
+        .reduce((acc, state) => {
+          acc[state] = (acc[state] || 0) + 1
+          return acc
+        }, {})
+      return WorkflowState.enumValues
+        .filter(state => state !== WorkflowState.UNINSTALLED)
```
Comment (hjoliver) [inline src/views/Dashboard.vue:242]: Remove line?
```suggestion
```

**Comment by dwsutherland** [comment]
I've had a look, and I can't reproduce the issue of the UI subscription:
```
subscription GscanSubscriptionQuery {
  deltas (stripNull: true, initialBurst: true) {
    ...GScanTreeDeltas
  }
}

# GSCAN DELTAS BEGIN

fragment GScanTreeDeltas on Deltas {
  id
  shutdown
  added {
    ...GscanAddedData
  }
  updated {
    ...GscanUpdatedData
  }
  pruned {
    workflow
  }
}

fragment GscanAddedData on Added {
  workflow (deltaStore: true) {
    ...WorkflowData
  }
}

fragment GscanUpdatedData on Updated {
  workflow (deltaStore: true) {
    ...WorkflowData
  }
}

fragment WorkflowData on Workflow {
  id
  name
  status
  owner
  host
  port
  stateTotals
  latestStateTasks(states: [
    "failed",
    "preparing",
    "submit-failed",
    "submitted",
    "running"
  ])
}
```
not getting the `installed` delta...

I've installed and removed the workflow so many times.. and all subscriptions get the `pruned.workflow`/`installed`

**Comment by kinow** [comment]
Posted on Element, but just FWIW, I disabled the Dashboard subscription, and then the issue went away. Looks like you need two subscriptions at least to reproduce it :+1:

**Comment by dwsutherland** [comment]
As mentioned on element it's a more general problem of the UI subscriptions (or at least the first two) sharing the same request, so have opened a new issue:
https://github.com/cylc/cylc-ui/issues/685

**Comment by kinow** [comment]
Rebased.

**Comment by oliver-sanders** [comment]
Hmm, all my workflows are showing as stopped at the moment:

Screenshot 2021-06-10 at 12 48 03

(a=stopped, b=paused, c=running)

**Comment by oliver-sanders** [comment]
I'm getting some stuck workflow states in GScan.

Here's an example of a workflow which is paused. The Tree View can tell it is paused (the play button is showing and live data is showing) but GScan thinks it is installed (the folder icon is showing):

Screenshot 2021-06-10 at 13 02 13

From GraphiQL query:

```json
{
  "data": {
    "workflows": [
      {
        "id": "oliver|one",
        "status": "paused"
      }
    ]
  }
}
```

Steps to replicate.

1. `cylc install <flow>`
2. `cylc play --pause <flow>`

**Comment by kinow** [comment]
Something strange with reactivity. Found at least one bug in the `if/else` logic (used `if/else`, had to be separated `if`'s). I'm seeing stale states too, although the data appears to be corrected merged now. Will look at this tomorrow or next week.

Thanks for testing @oliver-sanders ! Looks like it at least removed the workflow correctly. I will add tests, squash, and find what's wrong. Next review should be the final one.

File: src/components/cylc/tree/deltas.js [hunk 6]
```diff
@@ -15,96 +15,62 @@
...
-          // eslint-disable-next-line no-console
-          console.error('Error applying pruned-delta, will continue processing the remaining data', error, id)
-          store.dispatch('setAlert', new AlertModel('Error applying pruned-delta, see browser console logs for more. Please reload your browser tab to retrieve the full flow state', null, 'error'))
-        }
-      }
-    }
-  })
-}
+} from '@/components/cylc/tree/nodes'
+import * as CylcTree from '@/components/cylc/tree/index'
```
Comment (kinow) [inline src/components/cylc/tree/deltas.js:26]: We cannot keep the state of the `CylcTree` in an object along with functions/methods. That's because we are now storing it in Vuex store, which doesn't allow functions/methods in the stored data :+1: The way the code is imported here, is very similar to how you can specify functions in a module in Python and call them directly. It looks like an Object, but is not really an instance with a constructor and local state.

File: src/components/cylc/tree/deltas.js [hunk 7]
```diff
@@ -181,71 +176,76 @@ function handleInitialDataBurst (deltas, tree) {
...
+    if (deltas[key]) {
+      const handlingFunction = DELTAS[key]
+      const result = handlingFunction(deltas.added, workflow, lookup, options)
+      errors.push(...result.errors)
+    }
+  })
   // if added, removed, or updated deltas, we want to re-calculate the cycle point states now
   if (deltas.pruned || deltas.added || deltas.updated) {
-    tree.tallyCyclePointStates()
+    // FIXME
```
Comment (kinow) [inline src/components/cylc/tree/deltas.js:194]: Note to self: remove this comment. I had commented the `tallyCyclePointStates()` call, and marked with a NOTE (the IDE highlights it, so it's easier for me to see what's pending), but forgot to remove the mark.

File: src/components/cylc/tree/deltas.js [hunk 8]
```diff
@@ -181,71 +176,76 @@ function handleInitialDataBurst (deltas, tree) {
...
     }
-  } else {
-    throw Error('Workflow tree subscription did not return data.deltas')
+  }
+  // the tree was created, and now the next messages should contain
+  // 1. new data added under deltas.added (but not in deltas.added.workflow)
+  // 2. data updated in deltas.updated
+  // 3. data pruned in deltas.pruned
+  try {
+    return handleDeltas(deltas, workflow, lookup, options)
```
Comment (kinow) [inline src/components/cylc/tree/deltas.js:239]: **Note**: We are handling only deltas, no more handling initial data burst. I have modified the queries to use a flat structure, and whether it's the initial burst or not, makes no difference to the UI. I simply add every data returned to a dictionary and store in Vuex. Other Vuex actions (e.g. `applyTreeDeltas`) can then access the dictionary and use it to retrieve created values from delta, avoiding this way creating new - and duplicated - data.

File: src/components/cylc/tree/index.js [hunk 9]
```diff
@@ -14,58 +14,542 @@
...
+/**
+ * @param {Workflow} workflow
+ */
+function clear (workflow) {
+  ['tree', 'lookup'].forEach(each => {
+    Object.keys(workflow[each]).forEach(key => {
+      Vue.delete(workflow[each], key)
+    })
+  })
+}
```
Comment (kinow) [inline src/components/cylc/tree/index.js:181]: Lots of changes in this file. But you can mostly ignore them. The summary of what was changed is the following:

- No more `CylcTree` object that hold a `tree` structure and a `lookup`
- The functions of the `CylcTree` object were re-wrote into functions that accept the same parameters as before, plus a `workflow` parameter
- The `workflow` parameter comes from Vuex store; it has the following structure: `{ tree: {}, lookup: {}  }`

The `workflow.lookup` contains all the **nodes** of the tree in a flat hashmap. The `workflow.tree` contains the same data, but following a hierarchy. The `.node` of each entry in both `.lookup` and `.tree` points to the `workflows/lookup` global state (there are two lookups, maybe will rename one later).

File: src/components/cylc/tree/nodes.js [hunk 10]
```diff
@@ -332,7 +332,8 @@ function createCustomOutputs (job) {
  * @return {JobNode}
  */
 function createJobNode (job) {
-  Vue.set(job, 'customOutputs', createCustomOutputs(job))
+  const customOutputs = createCustomOutputs(job)
+  Vue.set(job, 'customOutputs', customOutputs)
```
Comment (kinow) [inline src/components/cylc/tree/nodes.js:336]: Note to self: I had this change in my IDE when debugging, to see the value of `customOutputs` and confirm it was valid. This can probably be undone now.

File: src/components/cylc/workflow/Toolbar.vue [hunk 11]
```diff
@@ -165,14 +167,12 @@ export default {
...
-        name: 'tree',
-        title: 'Tree',
+        name: TreeView.name,
         icon: mdiFileTree
 
       },
       {
-        name: 'mutations',
-        title: 'Mutations',
+        name: MutationsView.name,
```
Comment (kinow) [inline src/components/cylc/workflow/Toolbar.vue:175]: We don't need the lower-case and upper-case variations. Easier to fire an event just with the name and also use it for displaying the value. Plus, this way we just need to update the `.name` in one place to get the views&components that use it to update too.

File: src/components/cylc/workflow/deltas.js [hunk 12]
```diff
@@ -0,0 +1,130 @@
...
+    errors.push(...result.errors)
+  }
+  if (pruned) {
+    const result = applyDeltasPruned(pruned, lookup)
+    errors.push(...result.errors)
+  }
+  return {
+    errors
+  }
+}
```
Comment (kinow) [inline src/components/cylc/workflow/deltas.js:130]: This file contains the deltas for `workflow`. `workflows/workflow` is stored in Vuex, and used by GScan, Dashboard, and WorkflowTable component/views (for now, since the data structure is similar for all views/components, but that can be easily changed now).

**Review by kinow — COMMENTED** [review]
Partially done a review for myself. Will continue work on Monday. But at the moment, this PR should address all feedback from previous reviews.

Plus, this should also fix several other issues that I will link on Monday. For instance:

- The flat-ish data is stored now in Vuex
- The subscriptions are kept in the Workflow Service
- Several new mixins are now used to control the lifecycle of subscriptions
- Workflow view simply adds new views; it does not care about the subscriptions

The size of the change will look intimidating once it's done (will have to add and update several tests), but I'm feeling quite confident that this will fix the GScan deltas and also allow us to incorporate the Table view PR more easily.

The reason for this big change, is that I realized that I would need yet another `deltasObservable` in the service for GScan. And that wouldn't look really nice once complete, and would have to be removed/fixed later when working on the Table PR.

More to come on Monday. I've hidden several of my previous comments to simplify the final review (which I may send the request next week) :+1:

**Comment by oliver-sanders** [comment]
Tested workflow state transitions, looks good, works as expected.

File: src/views/Workflow.vue [hunk 13]
```diff
@@ -52,37 +52,31 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 </template>
 
 <script>
```
Comment (kinow) [inline src/views/Workflow.vue:54]: This file will have mainly code being removed. This is because the behavior of views & components with subscriptions has been standardized, and is now in mixins and in the Workflow Service. I will write a couple paragraphs on how to add a view with a widget here, and use that later to update the Table view PR.

File: src/store/workflows.module.js [hunk 14]
```diff
@@ -25,24 +58,88 @@ const getters = {
...
+    }
+    result.errors.forEach(error => {
+      commit('SET_ALERT', new Alert(error[0], null, 'error'), { root: true })
+      // eslint-disable-next-line no-console
+      console.warn(...error)
+    })
+  },
+  clearTree ({ commit }) {
+    commit('CLEAR_WORKFLOW')
   }
```
Comment (kinow) [inline src/store/workflows.module.js:143]: The data used in views with subscriptions is all here now.

We have new actions & mutations to both populate the data, and to remove it. These actions are called by the mixins & Workflow Service. You only need to declare what you want in your view or component.

File: src/services/workflow.service.js [hunk 15]
```diff
@@ -34,29 +27,38 @@ import {
...
-class WorkflowService extends GQuery {
+class WorkflowService {
   /**
    * @constructor
    * @param {string} httpUrl
    * @param {SubscriptionClient|null} subscriptionClient
    */
   constructor (httpUrl, subscriptionClient) {
-    super()
-    this.query = null
```
Comment (kinow) [inline src/services/workflow.service.js:46]: Before the Workflow Service allowed a single query. Every other query would be merged back to this original query. Now it supports multiple queries. You can have 1 merged query (e.g. when you have Dashboard + GScan), or you can have 2 or more (e.g. when you have GScan, and also the other query for Tree/Table views, which uses variables like `{ workflowId : "kinow|five" }`. Note these variables cannot be applied to the GScan query as that would limit the data returned, hence the 2 subs/queries in this example).

File: src/services/workflow.service.js [hunk 16]
```diff
@@ -106,108 +245,131 @@ class WorkflowService extends GQuery {
...
-    const mutation = this.getMutation(mutationName)
-    return mutate(
-      mutation,
-      getMutationArgsFromTokens(
-        mutation,
-        tokenise(id)
-      ),
-      this.apolloClient
-    )
+  gClone (query) {
```
Comment (kinow) [inline src/services/workflow.service.js:317]: This function, and the next functions down are all from the old `gquery.js`. I just moved them here. We are not changing how we merge queries, I've reverted that change, but will create disabled unit tests for cases where the current approach could result in bugs, or where it's missing some feature :+1: For now it should work fine for what we need.

File: src/services/mock/json/OnWorkflowTreeDeltasData.json [hunk 17]
```diff
@@ -1,366 +1,354 @@
 {
-  "workflows": [
+  "workflow": {
```
Comment (kinow) [inline src/services/mock/json/OnWorkflowTreeDeltasData.json:2]: Flat data, same data that you should see in deltas!

File: src/router/index.js [hunk 18]
```diff
@@ -69,25 +70,35 @@ Vue.use(Meta)
...
-    })
+    router.app.$userService.getUserProfile()
+      .then((user) => {
+        store.commit('user/SET_USER', user)
+        next()
+      })
+      .catch(error => {
+        const alert = new Alert(error, null, 'error')
+        return store.dispatch('setAlert', alert)
+      })
```
Comment (kinow) [inline src/router/index.js:101]: We already had a dependency/relationship between the router here and the store. Returning the user  in the User Service, eliminates the dependency between User Service and the store, making it easier to test.

File: src/model/ViewState.model.js [hunk 19]
```diff
@@ -0,0 +1,28 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import { Enumify } from 'enumify'
+
+class ViewState extends Enumify {
```
Comment (kinow) [inline src/model/ViewState.model.js:20]: Note to self: document.

File: src/model/SubscriptionQuery.model.js [hunk 20]
```diff
@@ -0,0 +1,38 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+// eslint-disable-next-line no-unused-vars
+import { DocumentNode } from 'graphql'
+
+class SubscriptionQuery {
```
Comment (kinow) [inline src/model/SubscriptionQuery.model.js:21]: Note to self: document.

File: src/model/Subscription.model.js [hunk 21]
```diff
@@ -0,0 +1,71 @@
...
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import ViewState from '@/model/ViewState.model'
+import Alert from '@/model/Alert.model'
+
+class Subscription {
```
Comment (kinow) [inline src/model/Subscription.model.js:21]: Note to self: document

File: src/mixins/subscriptionView.js [hunk 22]
```diff
@@ -0,0 +1,46 @@
...
+      // }
+      vm.$workflowService.startSubscriptions()
+    })
+  }
+  // beforeRouteLeave (to, from, next) {
+  //   if (this.query && this.query.query) {
+  //     this.$workflowService.unsubscribe(this)
+  //   }
+  //   next()
+  // }
```
Comment (kinow) [inline src/mixins/subscriptionView.js:45]: Note to self: TODO

File: src/mixins/subscriptionComponent.js [hunk 23]
```diff
@@ -0,0 +1,30 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import subscriptionMixin from '@/mixins/subscription'
+
+export default {
```
Comment (kinow) [inline src/mixins/subscriptionComponent.js:20]: Note to self: document

File: src/mixins/subscriptionView.js (hunk 22 above)
Comment (kinow) [reply src/mixins/subscriptionView.js:45]: Aaaand document.

File: src/mixins/subscription.js [hunk 24]
```diff
@@ -0,0 +1,35 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+import ViewState from '@/model/ViewState.model'
+import { mapActions } from 'vuex'
+
+export default {
```
Comment (kinow) [inline src/mixins/subscription.js:20]: Note to self: document.

File: src/layouts/Default.vue [hunk 25]
```diff
@@ -74,7 +73,7 @@ export default {
 
   errorCaptured (error, vm, info) {
     if (process.env.NODE_ENV !== 'production') {
-      store.dispatch('setAlert', new AlertModel(error, null, 'error'))
+      vm.$store.dispatch('setAlert', new AlertModel(error, null, 'error'))
```
Comment (kinow) [inline src/layouts/Default.vue:76]: Note to self: undo this change.

File: src/graphql/queries.js [hunk 26]
```diff
@@ -169,68 +108,130 @@ fragment JobData on Job {
...
+}
+
+${WORKFLOW_DATA_FRAGMENT}
 `
 
 export {
   WORKFLOW_TREE_DELTAS_SUBSCRIPTION,
-  DASHBOARD_QUERY,
-  GSCAN_QUERY,
-  WORKFLOWS_TABLE_QUERY
```
Comment (kinow) [inline src/graphql/queries.js:235]: Note to self: add the queries even though they won't result in a different `root` query?

File: tests/unit/components/cylc/tree/index.spec.js [hunk 27]
```diff
@@ -62,11 +80,11 @@ describe('Tree component functions', () => {
...
-    const tree = {}
-    const workflow = {}
-    expect(populateTreeFromGraphQLData, null, workflow).to.not.throw(Error)
-    expect(populateTreeFromGraphQLData, tree, null).to.not.throw(Error)
-    expect(populateTreeFromGraphQLData, tree, workflow).to.not.throw(Error)
+    // const tree = {}
+    // const workflow = {}
+    // expect(populateTreeFromGraphQLData, null, workflow).to.not.throw(Error)
+    // expect(populateTreeFromGraphQLData, tree, null).to.not.throw(Error)
+    // expect(populateTreeFromGraphQLData, tree, workflow).to.not.throw(Error)
```
Comment (kinow) [inline tests/unit/components/cylc/tree/index.spec.js:87]: Note to self: undo?

File: src/graphql/queries.js (hunk 26 above)
Comment (kinow) [reply src/graphql/queries.js:235]: Dashboard added back.

File: src/components/cylc/tree/nodes.js [hunk 28]
```diff
@@ -343,24 +343,11 @@ function createJobNode (job) {
...
-    workflow.taskProxies && Array.isArray(workflow.taskProxies)
-}
-
 export {
   createWorkflowNode,
   createCyclePointNode,
   createFamilyProxyNode,
   createTaskProxyNode,
   createJobNode,
-  containsTreeData,
```
Comment (kinow) [inline src/components/cylc/tree/nodes.js:364]: Not used. Or, we could — in theory — use it to filter out empty deltas, see #689 But then TUI would have to do something similar. I think it would be best if we didn't receive any deltas after `shutdown: true`, unless it's a new initial burst.

File: src/components/core/Alert.vue [hunk 29]
```diff
@@ -56,8 +55,12 @@ export default {
   },
 
   methods: {
+    ...mapActions(['setAlert']),
     getColor (type) {
       return this.colors.get(type) || ''
+    },
+    closeAlert () {
+      this.setAlert(null)
```
Comment (kinow) [inline src/components/core/Alert.vue:63]: This is fixing #625 . See the `@click` in the Vuetify Alert component, which is bound to this `closeAlert` function, effectively removing the alert from the store too :+1: e2e test added for this.

File: src/components/core/Alert.vue [hunk 30]
```diff
@@ -56,8 +61,19 @@ export default {
...
     getColor (type) {
       return this.colors.get(type) || ''
+    },
+    /**
+     * Dismisses the alert from the UI, also removing it from the Vuex store.
+     *
+     * @param {Function} toggleFunction - the original Vuetify toggle function
+     * @see https://vuetifyjs.com/en/api/v-alert/
+     */
+    closeAlert (toggleFunction) {
```
Comment (kinow) [inline src/components/core/Alert.vue:74]: This is fixing #625 . See the `@click` in the Vuetify Alert component, which is bound to this `closeAlert` function, effectively removing the alert from the store too :+1: e2e test added for this.

(`toggleFunction` is the `toggle` function slot prop from the Vuetify docs, which was called before to remove the Alert component from the UI.... we still call that, but first we remove the alert from the Vuex store...)

**Comment by kinow** [comment]
@hjoliver @oliver-sanders this is now ready for review :tada: 

I linked the issues fixed in this PR at the top-most comment, adding a comment to each list item about where the review would happen. For most, you will have to read the code. But some issues can be reviewed running this branch with a running workflow, and using the browser tools & extensions.

There's an error message added for every cycle point in my `five` workflow. That's because the job finishes too soon, and the delta includes it in added, updated, and in the pruned sections. See Protocols element room on-going chat with @dwsutherland about it. I can add extra code to hide that message, but TUI would have to do the same if it re-used a delta (as well as other users/clients of our GraphQL endpoint), or we could filter those entities from the deltas - **pending**

I tested the following:

- linter OK
- unit tests OK
- e2e tests OK (`mutation.js` was brittle, failing occasionally when it failed to locate a DOM element; fixed now :crossed_fingers: )
- code review (reviewed the code last week, then fixed tests this week, and yesterday did a final code review of my own changes & PR comments that I had added with "Note to self" :grimacing: )
- manual tests
  * `five` workflow installed, then started
  * used tree view for the `five` workflow
  * stopped it, GScan and tree appear to be OK
  * `cylc install` another workflow, GScan shows the new workflow as installed
  * `cylc play --pause $workflow` now GScan shows the workflow's new status correctly
  * `cylc stop $workflow`, also OK
  * `cylc clean $workflow` all good too
  * `cylc install` the same workflow again
  * rm -rf ~/cylc-run/$workflow, workflow disappears from GScan
  * Installed 4 workflows, having 2 playing (being paused too), GScan and the Tree components both showing the correct status as far as I could tell, and GraphiQL is correct too

I hid several old comments where I was saying things like "Rebased", or "Tests are fixed", etc. Just to make review simpler. But note that there are 2 comments of Codecov. To see the latest coverage, you need to click on the "Read more" link in GitHub to find Codecov's latest comment (see the edit history dropdown for the date, it should be a few hours/days old). Or access https://app.codecov.io/gh/cylc/cylc-ui/compare/543.

Thanks!

**Comment by kinow** [comment]
Rebased after merging @oliver-sanders 's fix for the mutations directive. Also spotted a typo in `CHANGES.md` so included an extra small commit :+1:

**Comment by oliver-sanders** [comment]
Did some heavy testing, no issues so far 🍾.

It is very satisfying watching the job states update in GScan:

gscan

**Comment by oliver-sanders** [comment]
Code is looks really good, I like the mixins, made it most the way through today, will come back to it Monday.

File: CHANGES.md [hunk 31]
```diff
@@ -10,14 +10,16 @@ release.
...
+[#656](https://github.com/cylc/cylc-ui/pull/656) - Show runahead-limited tasks.
 
 [#657](https://github.com/cylc/cylc-ui/pull/657) - Display a different icon, with
 a shadow underneath, for the Job component.
 
 [#658](https://github.com/cylc/cylc-ui/pull/658) - Allow user to set the order
 of cycle points.
 
+[#543](https://github.com/cylc/cylc-ui/pull/543) - Use deltas in GScan.
+
```
Comment (kinow) [inline CHANGES.md:22]: This pull request solves several issues. After this gets merged, I will go through each issue updating it, and then create another PR with the changelog. I'm not sure if we won't have to drop some changes, so I didn't want to include the text here now and then maybe have to remove it later.

**Review by oliver-sanders — COMMENTED** [review]
Made it to the end 😓.

Looks great, the queries and subs are nicely centralised and the mixins should make view development easier :+1:.

Still need to dive into the subscription merging (unexpected bonus 🎉). To help me review this could you comment about what the subscription merging is supposed to merge and what it isn't (i.e. what subscriptions we should expect to have for different views).

Still need to do some hands on testing with:

* Lookup / tree structures.
* Subscription merging.
* Delta processing.

I have only found a couple of small snags so far which are to do with the life cycle of subscriptions.

Here's the diff I used for testing (you may need to correct me if my method is wrong):

```diff
diff --git a/src/services/workflow.service.js b/src/services/workflow.service.js
index 455f60e8..ccdf521c 100644
--- a/src/services/workflow.service.js
+++ b/src/services/workflow.service.js
@@ -203,6 +203,8 @@ class WorkflowService {
     } catch (e) {
       subscription.handleViewState(ViewState.ERROR, e)
     }
+
+    console.warn('# START', this.subscriptions)
   }
 
   /**
@@ -271,6 +273,7 @@ class WorkflowService {
       store.dispatch(actionName).then(() => {})
     })
     delete this.subscriptions[subscription.query.name]
+    console.warn('# STOP', this.subscriptions)
   }
 
   // --- Merging GraphQL queries...
```

> **Note:** This logs the subscriptions AFTER a subscription has been started or stopped.

And here are my results:

> **Experiment 1:** Move from the Dashboard to workflow page.
>
> The "root" subscription is cancelled and re-started causing GScan to flicker.

Screenshot 2021-06-28 at 15 52 38

> **Experiment 2:** Open new tree views
>
> (Note: to replicate this I had to start on the Dashboard page)
>
> The "root" subscription is canceled and re-started.

Screenshot 2021-06-28 at 15 57 59

**Comment by kinow** [comment]
Having some spare time this week after the work on this PR, and don't want to add more PR's that will cause this PR to have to be rebased or its merge delayed. So decided to cover a part of the new code that I thought wasn't too important to add tests initially (but doesn't hurt to have more tests right :) Last commit only includes a handful new unit tests, no changes to the code.

File: src/components/cylc/gscan/WorkflowIcon.vue [hunk 32]
```diff
@@ -42,9 +52,13 @@ export default {
      * @returns {String} - status, one of the WorkflowState enum values
      */
     getIcon () {
-      return (
-        WorkflowState.enumValueOf(this.status.toUpperCase()) ||
-        WorkflowState.ERROR).icon
+      // TBD: enumValueOf returned the wrong value?
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/gscan/WorkflowIcon.vue:55]: This is some crazy bug that I cannot explain at the moment. But using `enumValue for `WorkflowState` was returning the wrong value for me :confused: 

Will test again to confirm it was not some reactivity error (I hit this bug before I had the final version of this PR).

File: src/components/cylc/tree/deltas.js [hunk 33]
```diff
@@ -116,60 +82,96 @@ const UPDATED = {
...
- * @property {?DeltasAdded} added
- * @property {?DeltasUpdated} updated
- * @property {?DeltasPruned} pruned
+ * Helper object used to iterate pruned deltas data.
  */
+const PRUNED = {
+  jobs: 'removeJob',
+  taskProxies: 'removeTaskProxy',
+  familyProxies: 'removeFamilyProxy'
+}
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/tree/deltas.js:137]: I mentioned that to @dwsutherland yesterday on Element. But at the moment we are not handling when the workflow is removed in the tree. This code is being moved, but I agree we probably need to handle the removed. To be done in a follow-up, likely the #689 since I will be working on the deltas again.

File: src/components/cylc/workflow/Toolbar.vue [hunk 34]
```diff
@@ -165,14 +167,12 @@ export default {
     },
     views: [
       {
-        name: 'tree',
-        title: 'Tree',
+        name: TreeView.name,
         icon: mdiFileTree
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/workflow/Toolbar.vue:171]: Ah, this is related to the #376 issue. I left a comment at the top for you about it. I started to fix that here, but the change was getting a bit bigger. So I left only the initial work in this PR to simplify it, and moved the diff of what I had to this comment: https://github.com/cylc/cylc-ui/issues/376#issuecomment-868001793

Is that related to your suggestion about? WDYT?

File: src/model/Subscription.model.js [hunk 35]
```diff
@@ -0,0 +1,85 @@
...
+  handleViewState (viewState, context) {
+    const _this = this
+    if (viewState !== ViewState.ERROR) {
+      Object.values(this.subscribers).forEach(subscriber => {
+        subscriber.viewState = viewState
+      })
+    } else {
+      Object.values(this.subscribers).forEach(function (subscriber) {
+        subscriber.viewState = viewState
+        subscriber.setAlert(new Alert(context.message, null, 'error'))
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/model/Subscription.model.js:75]: The issue where we were showing only 1 error has been fixed here. Now it shows every alert added to the store.

A new alert replaces the last one. At the moment, you probably won't see all the alerts as Vue & the browser's DOM both batch changes like that. The alert component should display the last error in the subscribed view, but every error should be logged to the console (`setAlert` calls the Vuex store that calls `console`)

[the remark this answers is not in the document]
Comment (kinow) [reply src/model/Subscription.model.js:75]: For a follow-up, I think it would be nice if the user could see all the recent errors in some place in the UI, without having to open the browser console. Or maybe have a function that exports all the alerts (or with a limit of last-10, in case the user has like thousands of errors logged) so that that can be reported back to us.

File: src/services/workflow.service.js [hunk 36]
```diff
@@ -106,108 +245,131 @@ class WorkflowService extends GQuery {
...
+    const initialQuery = print(baseSubscriber.query.query)
+    subscription.query.query = baseSubscriber.query.query
+    subscription.actionNames = baseSubscriber.query.actionNames
+    subscription.tearDownActionNames = baseSubscriber.query.tearDownActionNames
+
+    subscribers.slice(1)
+      .forEach(subscriber => {
+        if (!isEqual(subscriber.query.variables, baseSubscriber.query.variables)) {
+          throw new Error('Error recomputing subscription: Query variables do not match.')
+        }
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/services/workflow.service.js:301]: Ah, gotcha. I have a few post-its with questions about the merging of graphql queries, including the variables. There are other cases like directives and arguments that we need to decide what's the strategy for merging in a query, or if we start filtering... it'll be fun to work on this :nerd_face: 

Will keep that in mind :+1:

File: src/views/Workflow.vue [hunk 37]
```diff
@@ -130,70 +111,48 @@ export default {
...
+      switch (view) {
+      case TreeView.name:
+        Vue.set(this.widgets, createWidgetId(), TreeView.name)
+        break
+      case MutationsView.name:
+        Vue.set(this.widgets, createWidgetId(), MutationsView.name)
+        break
+      default:
         throw Error(`Unknown view "${view}"`)
       }
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Workflow.vue:148]: @oliver-sanders I think the `name` would end up always being the `MutationsView.name` name? Planning to fix this as a follow-up here: https://github.com/cylc/cylc-ui/issues/376#issuecomment-868001793 WDYT?

File: src/views/Workflow.vue [hunk 38]
```diff
@@ -35,8 +35,8 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
           type="list-item-three-line"
           tab-title="tree"
         >
-          <tree-component
-            :workflows="tree.root.children"
+          <tree-view
+            :workflow-name="workflowName"
           />
         </v-skeleton-loader>
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Workflow.vue:41]: Yup! Done here: https://github.com/cylc/cylc-ui/issues/376#issuecomment-868001793

And in the diff I've used `<component :is ... >` too! So looks like we are thinking in a similar way :) I started doing that here, but the change was getting a bit bigger, and would require more unit/e2e tests, so I postponed it... but I will be honest that probably I should have done it earlier, as this PR is already a little bloated (sorry!).

What do you think if once it's merged I started working on these improvements and we review it again?

File: src/views/Guide.vue [hunk 39]
```diff
@@ -163,8 +163,11 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 import Task from '@/components/cylc/Task'
 import Job from '@/components/cylc/Job'
 import { TaskStateUserOrder } from '@/model/TaskState.model'
+import subscriptionViewMixin from '@/mixins/subscriptionView'
 
 export default {
+  name: 'Guide',
+  mixins: [subscriptionViewMixin],
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Guide.vue:170]: Ah, that's the not-so-nice part of this design. We need `subscriptionViewMixin` for the view if it contains any GraphQL subscription query.

For the Guide page, it shows GScan, which requires us to include this mixin. I couldn't find a better way… 

With these mixins, we should be able to update to Vue 3 with none or very minimal changes. But with Vue3 we should be able to replace it by the composition API. Maybe that will give us another way to define this that will be more elegant. :disappointed_relieved:

File: src/views/Dashboard.vue [hunk 40]
```diff
@@ -232,68 +240,20 @@ export default {
...
-       */
-      this.isLoading = !isActive
+      const count = Object.values(this.workflows)
+        .map(workflow => workflow.status)
+        .reduce((acc, state) => {
+          acc[state] = (acc[state] || 0) + 1
+          return acc
+        }, {})
+      return WorkflowState.enumValues
+        .sort((left, right) => left.name.localeCompare(right.name))
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Dashboard.vue:250]: We can do that way too.

When you define enums, they get a `enumOrdinal` number value automatically assigned. So we would just need to define the enums, in the order we want to see in the UI I think. Should I do it here or as follow-up?

File: src/store/workflows.module.js [hunk 41]
```diff
@@ -25,24 +54,88 @@ const getters = {
...
 const actions = {
-  set ({ commit }, data) {
-    commit('SET', data)
+  setWorkflowName ({ commit }, data) {
+    commit('SET_WORKFLOW_NAME', data)
+  },
+  applyWorkflowsDeltas ({ commit, state }, data) {
+    // modifying state directly in an action results in warnings...
+    const workflows = Object.assign({}, state.workflows)
+    applyDeltasGScan(data, workflows)
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:95]: For now yes. But maybe it should be named `applyDeltasWorkflows`? WDYT?

File: src/store/workflows.module.js [hunk 42]
```diff
@@ -14,9 +14,38 @@
...
+import applyDeltasLookup from '@/components/cylc/workflow/deltas'
+import applyDeltasTree from '@/components/cylc/tree/deltas'
+import Alert from '@/model/Alert.model'
+import { clear } from '@/components/cylc/tree/index'
 
 const state = {
+  /**
+   * @type {Object.<String, Object>}
+   */
+  lookup: {},
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:27]: Oh, my bad. I had a checkbox in one of the hidden comments to add comments, and then I only added a comment with the type :man_facepalming: . Let me fix this.

File: src/store/workflows.module.js [hunk 43]
```diff
@@ -14,9 +14,38 @@
...
+   * contains hierarchy, while the lookup (not workflow.lookup) is flat-ish.
+   *
+   * The nodes in the .tree property have a reference or pointer (.node) to the
+   * data in the lookup map above, to avoid data duplication.
+   *
+   * @type {Workflow}
+   */
+  workflow: {
+    tree: {},
+    lookup: {}
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:48]: Ah, mea culpa too, I'm horrible naming things.

The `workflows/lookup` is the workflow view lookup used to look up GraphQL raw data. The idea is for components like Tree & Table to re-use the data in `workflows/lookup` as pointers, instead of duplicating it.

The `workflows/workflow` holds the data for a Tree view. Its`workflows/workflow.tree` contains just a single root node (workflow) that contains children data (hierarchical data).

And `workflows/workflow.lookup` is used as a lookup of tree nodes. When you add a new node to the tree, instead of using the `node.children`, we just grab the parent node from `workflows/workflow.lookup` and add the new node as child.

The new node will have `{ id: bla, node: $POINTER_TO_WORKFLOWS_LOOKUP_DATA, children: [] }`.

Hope this makes sense, and happy to update these names (just don't trust me to choose better names :laughing: )

File: src/components/cylc/tree/deltas.js (hunk 33 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/components/cylc/tree/deltas.js:137]: No probs, so long as it's on a ticket somewhere.

File: src/views/Dashboard.vue (hunk 40 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/views/Dashboard.vue:250]: Can be follow up if it detracts from this PR, not critical but good for usability.

File: src/views/Guide.vue (hunk 39 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/views/Guide.vue:170]: > For the Guide page, it shows GScan, which requires us to include this mixin. I couldn't find a better way…

Yikes, I hadn't realised that!

I'm guessing we can't just use the mixin on the top-level App.

File: src/views/Workflow.vue (hunk 38 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/views/Workflow.vue:41]: Ah yes, I had seen that diff but forgotten :facepalm:, great!

File: src/views/Workflow.vue (hunk 37 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/views/Workflow.vue:148]: Ah, whoops, copy and paste error, I meant to use the string argument provided to the function:

```diff
-Vue.set(this.widgets, createWidgetId(), MutationsView.name)
+Vue.set(this.widgets, createWidgetId(), view)
```

Fine to do later.

[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Workflow.vue:148]: Ah, perfect, that's exact what I did in the diff :+1:

File: src/views/Guide.vue (hunk 39 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Guide.vue:170]: Correct, we have at least 1 page that doesn't use any subscription, the 404 page. Not sure if we will have more pages like that.

File: src/store/workflows.module.js (hunk 41 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:112]: Will update it tomorrow (also need to look at a TODO for an enum that I couldn't finish today)

File: src/components/cylc/workflow/Toolbar.vue (hunk 34 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/components/cylc/workflow/Toolbar.vue:171]: > Is that related to your suggestion about?

Yep

File: src/store/workflows.module.js (hunk 43 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/store/workflows.module.js:48]: That makes sense, thanks for explaining. I think those names are great, just getting my head around the distinction between the `workflows` and `workflow` levels.

I guess with the hierarchical GScan we would add another `tree` structure at the `workflows` level.

[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:48]: >I guess with the hierarchical GScan we would add another tree structure at the workflows level.

Yup, probably a very similar structure (since GScan re-uses the Tree component) :+1:

File: src/views/Dashboard.vue (hunk 40 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/views/Dashboard.vue:250]: Created follow-up issue https://github.com/cylc/cylc-ui/issues/693

File: src/components/cylc/tree/index.js [hunk 44]
```diff
@@ -14,58 +14,548 @@
...
+
+/**
+ * @param {Workflow} workflow
+ * @param {CyclePointNode} cyclePoint
+ * @param {*} options
+ */
+function addCyclePoint (cyclePoint, workflow, options) {
+  const cyclePointsOrderDesc = options.cyclePointsOrderDesc !== undefined
+    ? options.cyclePointsOrderDesc
+    : DEFAULT_CYCLE_POINTS_ORDER_DESC
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/tree/index.js:227]: >Can move inside the if block below.

Good catch! done!

>Should this be applied at render rather than at tree build as I'm not sure how stable this will be if the user changes the preference?

Good question. At the moment it's implemented in a way where users have to visit the settings page, and reload the page with a tree view (if already open). Created an issue to track that: https://github.com/cylc/cylc-ui/issues/694

File: src/store/workflows.module.js (hunk 41 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/store/workflows.module.js:112]: Renamed!

File: src/components/cylc/workflow/Toolbar.vue (hunk 34 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/workflow/Toolbar.vue:171]: To be fixed in #376

File: src/components/cylc/gscan/GScan.vue [hunk 45]
```diff
@@ -470,15 +416,48 @@ export default {
...
+          // GraphQL will return all the task states possible in a workflow, but we
+          // only want the states that have an equivalent state for a job. So we filter
+          // out the states that do not exist for jobs, and that have active tasks in
+          // the workflow (no point keeping the empty states, as they are not to be
+          // displayed).
+          return jobStates.includes(stateTotal[0]) && stateTotal[1] > 0
+        })
+      const summary = workflowStates
+        .map(stateTotal => `${stateTotal[0]}, ${stateTotal[1]}`)
+        .join(',')
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/gscan/GScan.vue:451]: Ops, fixed! Thanks!

File: src/services/workflow.service.js [hunk 46]
```diff
@@ -67,17 +69,154 @@ class WorkflowService extends GQuery {
...
+
+    try {
+      // Then start subscription.
+      subscription.observable = this.startDeltasSubscription(
+        subscription.query.query,
+        subscription.query.variables,
+        {
+          next: function next (response) {
+            subscription.actionNames.forEach(actionName => {
+              store.dispatch(actionName, response.data).then(() => {})
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/services/workflow.service.js:192]: Hmm, I wonder if I didn't speak too fast about fixing the issue of loading forever when there are no workflows.

Re-reading the code, now I can see that I'm changing the state immediately after I create the subscription, before it receives the first message where you pointed.

@oliver-sanders I can move the `subscription.handleViewState(ViewState.COMPLETE, null)` call here. The only downside I can see is that it would call the Vuex code for every subscription, which would be a bit expensive if you have a lot of GraphQL messages... :thinking:

**Comment by kinow** [comment]
>Here's the diff I used for testing (you may need to correct me if my method is wrong):

@oliver-sanders I think your diff is correct. And the results of your test look correct to me. Initially, I re-used the GScan query for Dashboard & WorkflowTables. Which resulted in less subscriptions being stopped and started again, but then I thought it would be best to keep things as they are for now, and focus on getting the GScan component and the subscriptions in place first, leaving a few teaks like this one for later.

Probably to be addressed when we work on the new issues for query merging after this PR.

File: src/components/cylc/gscan/WorkflowIcon.vue (hunk 32 above)
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/gscan/WorkflowIcon.vue:55]: Still happening, and no idea why that's happening. Could be an error when webpack or babel are processing the code, but will have to look at that later.

https://github.com/cylc/cylc-ui/issues/695

File: src/components/cylc/gscan/GScan.vue [hunk 47]
```diff
@@ -296,6 +293,8 @@ export default {
               value: state,
               model: false
             }
+          }).sort((left, right) => {
+            return left.text.localeCompare(right.text)
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/components/cylc/gscan/GScan.vue:297]: Ah, good idea! Done!

File: src/services/mock/generate [hunk 48]
```diff
@@ -22,8 +22,10 @@ fi
 cd "$(dirname "$0")" || exit 1
 CHECK_FILE='json/OnWorkflowTreeDeltasData.json'
 
-cylc reg "one" one
-if cylc run "one" --fcp=20000102T0000Z --no-detach; then
+cylc install --flow-name="one" --no-run-name --directory=one
+mkdir "${HOME}/cylc-run/one/bin"
+cp checkpoint/get_checkpoint.py "${HOME}/cylc-run/one/bin/"
```
[the remark this answers is not in the document]
Comment (kinow) [reply src/services/mock/generate:27]: Is it `one/bin/get_checkpoint.py`, or `one/get_checkpoint.py`?

**Comment by oliver-sanders** [comment]
Looking back at the issues I mentioned above about subscriptions being cancelled and re-started.

Perhaps the solution to this is to make the "unregister subscription" logic schedule a callback rather than cancelling the sub straight away. The callback can then check whether any new view has subscribed to the sub in the mean time.

This way the GScan subscription wouldn't get cancelled. This leads onto the idea of keeping workflow subs active for a configured period so that users can switch back and forth between workflows with minimum waiting. Related to https://github.com/cylc/cylc-ui/issues/392

**Comment by kinow** [comment]
>looks like a bug on this branch causing the root sub to be cancelled when trying to add a workflow sub?

I thought the root subscription had been cancelled because the Dashboard query had been removed, resulting in a call to `recompute` and then triggering the stop/start in the subscription.

I will take a look tomorrow, but you are correct, it's supposed to stop `root` only iff the `root`'s query changed, not because of any changes to the `workflow` query.

**Comment by kinow** [comment]
@oliver-sanders found the bug that was causing the GScan `root` subscription to be stopped and started again! The subscription was marked as `reload = true` because of the merge of GScan + Dashboard queries.

The issue was that I was never setting `reload = false` :sweat_smile: 

Fixed, and found another bug where I was not saving the result of union's of collections. Fix is really small, but I will probably need a bit more of time to write tests for these 2 issues I just found, to prevent them from happening again :+1: 

Thanks!!!

**Comment by kinow** [comment]
Done! If tests pass in CI, it should not stop/start the root subscription when going from Dashboard to the Tree view or Workflow with Tree view :+1:

**Comment by oliver-sanders** [comment]
Brilliant that fixes both of my scenarios.

File: src/services/mock/generate (hunk 48 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/services/mock/generate:27]: `one/bin/get_checkpoint.py` (Cylc automatically adds the `bin/` directory to `$PATH`).

File: src/services/workflow.service.js (hunk 46 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply src/services/workflow.service.js:192]: I'm not worried about moving the state change, was just wondering if something had been missed.

> Hmm, I wonder if I didn't speak too fast about fixing the issue of loading forever when there are no workflows.

Have re-tested, no probs.

**Review by oliver-sanders — APPROVED** [review]
Great :champagne:, really nice code, should give us a pattern to grow into.

**Comment by kinow** [comment]
Thanks @oliver-sanders !

**Comment by hjoliver** [comment]
I'm having a good play with this, probably can't improve on @oliver-sanders ' thorough review. Looks great so far, massive effort to close so many issues, thanks @kinow :bouquet:

**Review by hjoliver — APPROVED** [review]
Very nice :+1:
