### PR TITLE
Fix incorrect nesting of hierarchical dirs in GScan

### LINKED ISSUE #930: gscan: only one level of the hierarchy is displayed
The workflow `a/b/c/d` displays differently at 0.6.0 to 1.0.0:

**0.6.0**

**1.0.0**

The 0.6.0 UI is correctly displaying all levels of the hierarchy whereas the 1.0.0 UI is only displaying one level.

This suggests we have a gap in testing which should be filled by the fix.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #930, fixing a bug where the GScan sidebar was only showing the top level of workflow directory trees.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Appropriate tests are included (unit and/or functional).
- [ ] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Review by wxtim — APPROVED** [review]
I will take the code apart for my own edification tomorrow, but the non language specific logic I can read, and the contents of debugger make sense.

Also, works empirically.

**Review by AaronDCole — APPROVED** [review]
Looks good, I cant reproduce the original issue so I think this works

**Comment by wxtim** [comment]
> I will take the code apart for my own edification tomorrow

I have now done this, and very edifying it was.

**Comment by oliver-sanders** [comment]
Looks good!

File: src/components/cylc/gscan/nodes.js [hunk 1]
```diff
@@ -97,29 +97,18 @@ function createWorkflowNode (workflow, hierarchy) {
...
-  }
-  const tokensThing = tokensList.slice(-1)[0]
-
-  // add the workflow to the bottom
-  children.push(
-    newWorkflowNode(workflow, tokensThing[0])
+  const leafNode = newWorkflowNode(workflow, tokensList.pop()[0])
+  // iterate over flat hierarchy list, creating node objects and nesting them
+  // (bottom to top):
+  const rootNode = tokensList.reduceRight(
```
Comment (oliver-sanders) [inline src/components/cylc/gscan/nodes.js:103]: v nice.

**Review by oliver-sanders — APPROVED** [review]
Manually tested and played with unit tests.

**Comment by MetRonnie** [comment]
Will add tests in a later PR
